### ISSUE TITLE
个人中心这个图标的粗细不对

### ISSUE THREAD

**Issue by ahu** [moyanxiu/shopApp#1]
这个图标的线型比其他三个要粗一点，可否调整为一致粗细？

**Comment by moyanxiu** [comment]
已经稍微调整了

**Comment by ahu** [comment]
下载跟其他几个对比了一下，还是粗一些，而且图片的模式也不一样。算了，就这样吧，也不是啥大问题:)
![qq20170803-182944](https://user-images.githubusercontent.com/330336/28917884-cf90c892-7879-11e7-8574-f7a125624625.png)

**Comment by moyanxiu** [comment]
已经重新换了图标了

**Comment by ahu** [comment]
这样啊，也不失为一个方法:)
